
name: Simple Data warehouse
services:
  production_postgres:
    image: postgres:16
    container_name: production_db
    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: xyz_store
    
    ports:
      - "5432:5432"
    volumes:
      - "./prod_db:/var/lib/postgresql/data"

  datawarehouse_postgres:
    image: postgres:16
    container_name: dwh
    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: xyz_store_wh
    
    ports:
      - "5433:5432"
    volumes:
      - "./wh_db:/var/lib/postgresql/data"

  # airflow:
  #   container_name: airflow_orchestrator
  #   image: apache/airflow:3.1.0
  #   ports:
  #     - 8000:8080
  #   environment:
  #   AIRFLOW__DATABASE__SQL__ALCHEMY_CONN:
