
name: Simple-Data-warehouse
services:
  production_postgres:
    image: postgres:16
    container_name: production_db
    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: xyz_store
    
    ports:
      - "5432:5432"
    volumes:
      - "./prod_db:/var/lib/postgresql/data"
    networks:
      - my-net

  datawarehouse_postgres:
    image: postgres:16
    container_name: dwh
    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: xyz_store_wh
    
    ports:
      - "5433:5432"
    volumes:
      - "./wh_db:/var/lib/postgresql/data"
      - "./airflow/airflow-init.sql:/docker-entrypoint-initdb.d/airflow-init.sql"
      - "./scripts/dw/init_wh_simple.sql:/docker-entrypoint-initdb.d/init_wh_simple.sql"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d xyz_store_wh"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my-net

  airflow:
    build: ./airflow
    container_name: airflow_orchestrator
    restart: always
    ports:
      - 8000:8080

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@datawarehouse_postgres:5432/airflow_db      
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./scripts/dw:/opt/airflow/dw
      
    depends_on:
      datawarehouse_postgres:
        condition: service_healthy

    networks:
      - my-net
    command: >
      bash -c "airflow db migrate && airflow standalone"

networks:
  my-net:
    driver: bridge